name: VS Market Place Deploy

on:
  push:
  pull_request:
    branches: [ master ]
  release:
    types:
      - created

env:
  machine: windows-latest
  nodeVersion: 10.x

jobs:
  build:
    if: github.event_name == push || github.event_name == pull_request

    name: Build

    runs-on: ${{ machine }}

    steps:
    - name: Use GitHub Actions
      uses: actions/checkout@v2
    - name: Use Node 10.x
      uses: actions/setup-node@v1
      with:
        node-version: ${{ nodeVersion }}
    - name: Install Dependencies
      run: npm install --prefix ./buildAndReleaseTask package.json
    - name: Build Task
      run: npm run build:prd --prefix ./buildAndReleaseTask

  artifact:
    if: github.event_name == create

    name: Generate Artifact

    needs: build

    runs-on: ${{ machine }}

    steps:
    - name: Use GitHub Actions
      uses: actions/checkout@v2
    - name: Use Node 10.x
      uses: actions/setup-node@v1
      with:
        node-version: ${{ nodeVersion }}

  publish:
    name: Pack and Publish

    needs: [build, artifact]

    runs-on: ${{ machine }}

    steps:
    - name: Use GitHub Actions
      uses: actions/checkout@v2
    - name: Use Node 10.x
      uses: actions/setup-node@v1
      with:
        node-version: ${{ nodeVersion }}