name: VS Market Place Deploy

on:
  push:
    branches: [ master ] 
  pull_request:
    branches: [ master ]

jobs:
  build:
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - run: npm install --prefix ./buildAndReleaseTask package.json
    - run: npm run build --prefix ./buildAndReleaseTask 
    - run: npm install -g tfx-cli
    - run: npm install -g json

  pack:
    if: github.base_ref == false
    needs: [build]

    runs-on: ubuntu-latest

    steps: 
    - name: Pack Extension
      uses: workflow/nix-shell-action@v1
      with:
        script: |
          rm -f temp.json
          echo "Start pack proccess"
          RESULT=$(tfx extension create --manifest-globs vss-extension.json --rev-version --json)
          echo "$RESULT" > temp.json

  update-resource:
    needs: [pack]

    runs-on: ubuntu-latest

    steps:
    - name: Update VSS Extension File
      uses: test-room-7/action-update-file@v1
      with:
        file-path: vss-extension.json
        commit-msg: Update resources
        github-token: ${{ secrets.GITHUB_TOKEN }}

  publish:
    needs: [update-resource]

    runs-on: ubuntu-latest

    steps:
    - name: Publish Extension
      run: |
        chmod +x ./scripts/publishExtension.sh
        ./scripts/publishExtension.sh ${{ secrets.VS_MARKET_PLACE_TOKEN }}
