name: VS Market Place Deploy

on:
  push:
    branches: 
    - 'master'
    - 'releases/**'
  pull_request:
    branches:
    - 'master'
    - 'releases/**'

jobs:
  build:
    if: ${{ github.ref == 'refs/heads/master' }}

    name: Build

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ windows-latest ]
        node: [ 10.x ]

    steps:
    - name: Use GitHub Actions
      uses: actions/checkout@v2
    - name: Use Node 10.x
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
    - name: Install Dependencies
      run: npm install --prefix ./buildAndReleaseTask package.json
    - name: Build Task
      run: npm run build --prefix ./buildAndReleaseTask

  artifact:
    if: ${{ github.ref == 'refs/heads/releases/**' }}

    name: Generate Artifact

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ windows-latest ]
        node: [ 10.x ]

    steps:
    - name: Use GitHub Actions
      uses: actions/checkout@v2
    - name: Use Node 10.x
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}

  publish:
    name: Pack and Publish

    needs: artifact

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ windows-latest ]
        node: [ 10.x ]

    steps:
    - name: Use GitHub Actions
      uses: actions/checkout@v2
    - name: Use Node 10.x
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}