name: VS Market Place Deploy

on:
  push:
  pull_request:
    branches: [ master ]
  release:
    types:
      - created

jobs:
  build:
    if: github.event_name == 'push' || github.event_name == 'pull_request'

    name: Build

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ windows-latest ]
        node: [ 10.x ]

    steps:
    - name: Use GitHub Actions
      uses: actions/checkout@v2
    - name: Use Node 10.x
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
    - name: Install Dependencies
      run: npm install --prefix ./buildAndReleaseTask package.json
    - name: Build Task
      run: tsc

  artifact:
    if: github.event_name == 'release'

    name: Generate Artifact

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ windows-latest ]
        node: [ 10.x ]

    steps:
    - name: Use GitHub Actions
      uses: actions/checkout@v2
    - name: Use Node 10.x
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}

  publish:
    if: github.event_name == 'release'

    name: Pack and Publish

    needs: artifact

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ windows-latest ]
        node: [ 10.x ]

    steps:
    - name: Use GitHub Actions
      uses: actions/checkout@v2
    - name: Use Node 10.x
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}