# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: VS Market Place Deploy

on:
  push:
    branches: [ master ] 
  pull_request:
    branches: [ master ]

jobs:
  build:
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - run: npm install --prefix ./buildAndReleaseTask package.json
    - run: npm run build --prefix ./buildAndReleaseTask 
    - run: npm install -g tfx-cli
    - run: npm install -g json

  pack:
    if: github.base_ref == false
    needs: [build]

    runs-on: ubuntu-latest

    steps:
    - name: 'Execute bash'
      run: packExtension.sh

  update-resource:
    needs: [pack]

    runs-on: ubuntu-latest

    steps:
    - name: Update VSS Extension File
      uses: test-room-7/action-update-file@v1
      with:
        file-path: vss-extension.json
        commit-msg: Update resources
        github-token: ${{ secrets.GITHUB_TOKEN }}


  publish:
    needs: [update-resource]

    runs-on: ubuntu-latest

    steps:
    - name: Publish Extension
      run: publishExtension.sh ${{ secrets.VS_MARKET_PLACE_TOKEN }}
